### ISSUE TITLE
IOError: image file is truncated

### ISSUE THREAD

**Issue by xiesiyuan** [martinarjovsky/WassersteinGAN#13]
when I was trying to train WGAN on Imagenet , I got this error.

[0/25][1/5631] Loss_D: -1.322320 Loss_G: 0.666666 Loss_D_real: -0.665913 Loss_D_fake 0.656407
[0/25][2/5631] Loss_D: -1.471963 Loss_G: 0.730293 Loss_D_real: -0.750265 Loss_D_fake 0.721698
[0/25][3/5631] Loss_D: -1.504353 Loss_G: 0.745277 Loss_D_real: -0.767033 Loss_D_fake 0.737320
[0/25][4/5631] Loss_D: -1.522664 Loss_G: 0.754508 Loss_D_real: -0.776120 Loss_D_fake 0.746544
[0/25][5/5631] Loss_D: -1.534124 Loss_G: 0.758739 Loss_D_real: -0.782926 Loss_D_fake 0.751198
[0/25][6/5631] Loss_D: -1.539814 Loss_G: 0.761637 Loss_D_real: -0.785868 Loss_D_fake 0.753947
[0/25][7/5631] Loss_D: -1.541982 Loss_G: 0.763071 Loss_D_real: -0.786177 Loss_D_fake 0.755805
[0/25][8/5631] Loss_D: -1.544353 Loss_G: 0.764505 Loss_D_real: -0.787565 Loss_D_fake 0.756788
[0/25][9/5631] Loss_D: -1.545964 Loss_G: 0.764762 Loss_D_real: -0.788965 Loss_D_fake 0.756999
[0/25][10/5631] Loss_D: -1.547822 Loss_G: 0.765548 Loss_D_real: -0.789867 Loss_D_fake 0.757955
[0/25][11/5631] Loss_D: -1.542095 Loss_G: 0.765476 Loss_D_real: -0.784480 Loss_D_fake 0.757615
[0/25][12/5631] Loss_D: -1.547668 Loss_G: 0.766164 Loss_D_real: -0.789187 Loss_D_fake 0.758481
[0/25][13/5631] Loss_D: -1.548513 Loss_G: 0.766813 Loss_D_real: -0.789454 Loss_D_fake 0.759059
[0/25][14/5631] Loss_D: -1.549405 Loss_G: 0.767250 Loss_D_real: -0.790068 Loss_D_fake 0.759336
[0/25][15/5631] Loss_D: -1.548578 Loss_G: 0.767710 Loss_D_real: -0.788655 Loss_D_fake 0.759923
IOError: image file is truncated

Traceback (most recent call last):
  File "main.py", line 178, in <module>
    data = data_iter.next()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 162, in __next__
    idx, batch = self.data_queue.get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 378, in get
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    return recv()
  File "/usr/local/lib/python2.7/dist-packages/torch/multiprocessing/queue.py", line 21, in recv
    buf = self.recv_bytes()

**Comment by xiesiyuan** [comment]
is this a PIL problem? may need change the code.

**Comment by soumith** [comment]
this looks like some files in your imagenet dataset are corrupted.

**Comment by xiesiyuan** [comment]
@soumith thx!
