### ISSUE TITLE
some problem run program in my tensorflow

### ISSUE THREAD

**Issue by wangchao12** [martinarjovsky/WassersteinGAN#43]
my name is wangchao nice to meet you.
run https://github.com/martinarjovsky/WassersteinGAN  in my tensorflow find a problem 

[jianglin@JULYEDU-GPU1 WassersteinGAN-master]$ python main.py --dataset lsun --dataroot [lsun-train-folder] --cuda
Namespace(Diters=5, adam=False, batchSize=64, beta1=0.5, clamp_lower=-0.01, clamp_upper=0.01, cuda=True, dataroot='[lsun-train-folder]', dataset='lsun', experiment=None, imageSize=64, lrD=5e-05, lrG=5e-05, mlp_D=False, mlp_G=False, n_extra_layers=0, nc=3, ndf=64, netD='', netG='', ngf=64, ngpu=1, niter=25, noBN=False, nz=100, workers=2)
mkdir: cannot create directory ‘samples’: File exists
Random Seed:  2745
Traceback (most recent call last):
  File "main.py", line 78, in <module>
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
  File "/usr/lib/python2.7/site-packages/torchvision/datasets/lsun.py", line 99, in __init__
    transform=transform))
  File "/usr/lib/python2.7/site-packages/torchvision/datasets/lsun.py", line 20, in __init__
    readahead=False, meminit=False)
lmdb.Error: [lsun-train-folder]/bedroom_train_lmdb: No such file or directory
 please give some advice

**Comment by mottosso** [comment]
See https://github.com/martinarjovsky/WassersteinGAN/issues/47#issuecomment-326971266
